webtalk_init -webtalk_dir F:\\Recent_Project\\gpsImode_Proj_2\\gpsImode_Proj.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期一 三月 26 22:06:38 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "rjgnjb0rtukl5q37ficcru3lrj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_31" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "31" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1522064437119" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1522064437119"
webtalk_add_data -client sdk -key uid -value "1522064461139" -context "sdk\\\\bsp/1522064461139"
webtalk_add_data -client sdk -key hwid -value "1522064437119" -context "sdk\\\\bsp/1522064461139"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1522064461139"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1522064461139"
webtalk_add_data -client sdk -key uid -value "1522064462413" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key hwid -value "1522064437119" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key bspid -value "1522064461139" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1522064462413"
webtalk_add_data -client sdk -key uid -value "1522064642052" -context "sdk\\\\application/1522064642052"
webtalk_add_data -client sdk -key hwid -value "1522064437119" -context "sdk\\\\application/1522064642052"
webtalk_add_data -client sdk -key bspid -value "1522064461139" -context "sdk\\\\application/1522064642052"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1522064642052"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1522064642052"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1522064642052"
webtalk_transmit -clientid 2722010315 -regid "" -xml F:\\Recent_Project\\gpsImode_Proj_2\\gpsImode_Proj.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\Recent_Project\\gpsImode_Proj_2\\gpsImode_Proj.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\Recent_Project\\gpsImode_Proj_2\\gpsImode_Proj.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
